name: codingbahasa_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Firebase packages
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # File handling
  file_picker: ^10.3.3
  open_file: ^3.3.2

  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^31.2.5

  # YouTube player
  youtube_player_flutter: ^9.1.3

  # WebView support
  webview_flutter: ^4.8.0
  flutter_inappwebview: ^6.1.5

  # URL launcher
  url_launcher: ^6.3.0

  # Internationalization
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
